### ISSUE TITLE
Allow other petal items besides the Weeping Blue ones.

### ISSUE THREAD

**Issue by MagmaSlime123** [JoshieGemFinder/Betweenlands-Redstone#12]
Title.

Petals such these should be allowed in the basket (The texture shouldn't be that hard to do, just take the blue petal part and change its color).

![2024-04-25_20 40 52](https://github.com/JoshieGemFinder/Betweenlands-Redstone/assets/51277766/4dd0fe2e-5abc-42ba-b0e8-58f2a0fca40b)

**Comment by JoshieGemFinder** [comment]
Unfortunately, this isn't possible due to technical reasons.  
The whole point of the petal basket is that it can be moved with pistons. If I were to add support for other types of petals (or for more than 15 in a single basket) I'd have to use a tile entity, meaning it could no longer be moved with pistons, completely removing the point of the block.
